." %nBlock  Description"
." %n-----  ------------------"
." %n 001   Core c3 words"
." %n 002   File handling words"
." %n 003   String words"
." %n 005   Screen words"
." %n 006   Utility words"
." %n 044   Accept"
." %n 200   Benchmarks"
." %n 999   This help"
